### ISSUE TITLE
netstandard project compat

### ISSUE THREAD

**Issue by dazinator** [aspnet/AspNetKatana#105]
Adding the Microsoft.Owin package to a netstandard2.0 or netcoreapp2.0 project:

![image](https://user-images.githubusercontent.com/3176632/29110555-e901463a-7cde-11e7-8a21-2ebeae59ef3b.png)

Will compatibility for these tfm's be added?

**Comment by ysmoradi** [comment]
I've added signalr, web api and bunch of other owin middlewares to .net core 2 app. Lots of things are working properly (Except Swagger, which has a few problems in rare scenarios, that I'm working to make them fixed in .net core 2)
This uses .net core 2 shim for full .net framework dlls & owin package for asp.net core, which is acceptable. Do you've any special problem?

**Comment by dazinator** [comment]
> owin package for asp.net core
That was my problem, I was using `Microsoft.Owin` - have switched to using `Micosoft.AspNetCore.Owin` and that has resolved it - thank you.
