### ISSUE TITLE
PhysicalFileSystem: very slow with many files

### ISSUE THREAD

**Issue by SeriousM** [aspnet/AspNetKatana#133]
Hi!
I just spent hours figuring out why the `PhysicalFileSystem` component is very slow when it comes to serve about 600+ files over ssl in selfhosted scenario for my unbundled angular app.
I tried to change the implementation of [PhysicalFileSystem+PhysicalFileInfo.CreateReadStream()](https://github.com/aspnet/AspNetKatana/blob/24aa43641adac57cb5bd523b77bdc0ced9f0455d/src/Microsoft.Owin.FileSystems/PhysicalFileSystem.cs#L213) to omit the `FileOptions.Asynchronous` flag and the files are served in perfect time now.

To be cleart:
* he files are served fine when there is no ssl at all
* the problem occurs when owin is launched on https or another reverse proxy (eg. traefik) is playing the role of ssl and owin is served with http

Is there a reason why the asynchronous flag is needed?

**Comment by Tratcher** [comment]
Interesting. How much does it vary for small vs large files? E.g. 1kb, 1mb, 1gb. Are your files primarily small?

**Comment by SeriousM** [comment]
The files represent a big angular app in development mode (only vendor stuff is bundled) where the ~600 files range from 1kb to 5kb.
The load process is like a burst where a few files are loaded at first (eg. index.html, jspm_packages/system.js, config.js) and all others once `System.import("app/app")` kicks in.
It's strange that this behavior is triggered by using ssl in/direct and doesn't happen with http only.
Please ask if you need more information!

**Comment by Tratcher** [comment]
The addition of ssl causes two side effects. 1) it requires quite a bit more CPU and 2) it limits the amount of data sent per packet to about 16kb. The reduced packet size is primarily a problem for otherwise larger packages over high latency connections. Either of these can cause backups in your network, but it's not clear why the Async file option would affect any of that.

I expect the Async file option would be more important for larger files. It's possible it introduces unnecessary overhead for smaller files, but I don't have any theories for how it would be related to ssl.

Does it get any faster after the first client? There could be an app warmup bottleneck.

**Comment by Tratcher** [comment]
@sebastienros This would be interesting to repro with Core.

**Comment by SeriousM** [comment]
I guess it's pretty easy to reproduce the issue by having an index.html with 600 script references to unique files to avoid caching. What would you men?

**Comment by Tratcher** [comment]
He is performance testing ASP.NET Core and this component was ported to Core a while ago.
https://github.com/aspnet/FileSystem/tree/dev/src/FS.Physical

**Comment by SeriousM** [comment]
With the same flags: https://github.com/aspnet/FileSystem/blob/dev/src/FS.Physical/PhysicalFileInfo.cs#L57

**Comment by muratg** [comment]
Closing this one as this has not seen recent activity. @SeriousM let us know if you found/worked around this!
