### ISSUE TITLE
nuget won't install it with net framework 4.5

### ISSUE THREAD

**Issue by gidmeister2** [aspnet/AspNetKatana#171]
I'm trying to migrate my asp.net project from sql-membership to identity.  To do this, I needed to install nuget packages such as:
Microsoft.aspnet.identity.owin
Microsoft.owin.security.google
Microsoft.owin.security.microsoftaccount

And I get a message that Microsoft.owin can't be installed because its not up to date with framework 4.5

**Comment by Tratcher** [comment]
It now requires 4.5.1.

**Comment by mqueirozcorreia** [comment]
@gidmeister2 
In order to use update-package on nuget you should change your package.config to limit upper version, as below:
<package id="Microsoft.Owin" version="3.1.0" targetFramework="net45" allowedVersions="[,4)" />

@Tratcher 
Will you list the framework 4.5.1 dependency in nuget page? There is nothing about this over there:
https://www.nuget.org/packages/Microsoft.Owin/

**Comment by Tratcher** [comment]
@mqueirozcorreia the nuget page UI is not something package authors have any control over. It primary shows target frameworks when your package targets multiple.

**Comment by Tratcher** [comment]
We've lowered the TFM back to net45.
