### ISSUE TITLE
Please respect HttpOnly / Secure options in SignOut cookie

### ISSUE THREAD

**Issue by i4rilu** [aspnet/AspNetKatana#234]
https://github.com/aspnet/AspNetKatana/blob/e2b18ec84ceab7ffa29d80d89429c9988ab40144/src/Microsoft.Owin/Infrastructure/ChunkingCookieManager.cs#L276
https://github.com/aspnet/AspNetKatana/blob/e2b18ec84ceab7ffa29d80d89429c9988ab40144/src/Microsoft.Owin/Infrastructure/ChunkingCookieManager.cs#L289

Please respect HttpOnly / Secure options when constructing SignOut cookie.
```csharp
new CookieOptions
{
   Path = options.Path,
   Domain = options.Domain,
   Expires = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc),
   HttpOnly = options.HttpOnly,
   Secure = options.Secure,
});
```

**Comment by Tratcher** [comment]
These options do not apply to signout cookies, the cookie is being deleted. Was this affecting a real client or was it only flagged by some automation?

**Comment by i4rilu** [comment]
This was flagged during the compliance scanning.
If options do not apply to signout cookie - it would be great to have more control on signout cookie in ChunkingCookieManager.
Current approach is just to copy-paste whole DeleteCookie() method.
Thank you!

**Comment by jesperkristensen** [comment]
I have changed my authentication cookie name to have the __Host- prefix to ensure cookie integrity. Now the cookie is not deleted when SignOut() is called.

The following response header is sent, but the browser ignores it because it is missing the Secure flag:
Set-Cookie: __Host-.AspNet.Cookies=; path=/; expires=Thu, 01-Jan-1970 00:00:00 GMT

(Tested in latest Firefox and Chrome)
