### ISSUE TITLE
Having `access_token` as a query string crashes our web app

### ISSUE THREAD

**Issue by irmbrady** [aspnet/AspNetKatana#322]
We have a .NET app (solution with WebForms, controllers and WebAPI) that uses the `Microsoft.Owin` nuget package. We recently upgraded from `v4.0.0` to `v4.1.0` and now our requests with `access_token` in the query string have stopped working.

The `access_token` query string is used by GoCardless and Stripe when linking accounts, so it is stopping our clients linking their payment provider to our web app.

Does anyone know what could be causing this, or a way to resolve it?

Thanks in advanced 🙇‍♂️

**Comment by Tratcher** [comment]
You're using OpenIdConnect?

Putting the access_token into the query string is prohibited by the OIDC spec.
https://github.com/aspnet/AspNetKatana/blob/9e9c44d0b0027cb58a3252a10ea93f25ccab32af/src/Microsoft.Owin.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs#L211-L222

This was allowed in 4.0 because at the time it didn't support any flows that used the query string (e.g. code flow), so it never checked it.

The Strip [docs](https://stripe.com/docs/connect/oauth-reference) look like they use an OAuth code flow. There shouldn't be an access token in the url. (You also should be using an OAuth implementation, not OpenIdConnect).

**Comment by irmbrady** [comment]
@Tratcher I believe we're using OAuth for both, but for whatever reason we have a named query string called `access_token` when linking our web app to GoCardless and Stripe (need to investigate further).

I am perfectly happy knowing why it is failing now, and will look into changing our code to accomondate the change in 4.1.0.

Thanks for the quick response!
