### ISSUE TITLE
Access-Control-Allow-Origin header NOT present on returned header

### ISSUE THREAD

**Issue by coleman-rik** [aspnet/AspNetKatana#325]
.Net framework 4.5.2 WebAPI project C#
When using the CORS support, no 'Access-Control-Allow-Origin' is present on returned header.

Even though Startup.cs contains:
app.UseCors(Microsoft.Owin.Cors.CorsOptions.AllowAll);

Alternatively, if I manually add this to the Web.config file:
```
<system.webServer>
    <httpProtocol>
        <customHeaders>
            <add name="Access-Control-Allow-Origin" value="*" />
        </customHeaders>
    </httpProtocol>
</system.webServer>
```

I will get a header equal to "*, http:<calling_origin>".  Unfortunately this causes an invalid "Access-Control-Allow-Origin" header, since it now contains multiple values.

The request contains the correct value in the Origin header.
Any idea how to get this to work correctly?

Thanks,

**Comment by anurse** [comment]
> I manually add this to the Web.config file:
> ...
> I will get a header equal to "*, http:<calling_origin>". Unfortunately this causes an invalid "Access-Control-Allow-Origin" header, since it now contains multiple values.

Yeah, that is expected since the `web.config` has set the value to `*` and Owin CORS is adding it's value.


> When using the CORS support, no 'Access-Control-Allow-Origin' is present on returned header.

This is probably the underlying issue. Can you post a runnable sample that reproduces the problem? That way we know exactly what you've got configured. When you use `AllowAll` I believe it's supposed to reflect the value of the `Origin` header in the request to the `Access-Control-Allow-Origin` header in the response.
